{% set name = "premai" %}
{% set version = "0.3.67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/premai-{{ version }}.tar.gz
  sha256: 8bb24a36aca415551167a0f6d42828829b2fe8bc3452726d8418f513059f81d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - httpx >=0.20.0,<0.27.0
    - attrs >=21.3.0
    - python-dateutil >=2.8.0,<3.0.0
    - typing_extensions >=4.9.0

test:
  imports:
    - premai
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A client library for accessing Prem APIs
  home: https://github.com/premAI-io/prem-python-sdk
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
