schema_version: 1

context:
  name: premai
  version: "1.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/premai-${{ version }}.tar.gz
  sha256: 0d7df28b7bcbe80ea570a29647449827b8e92fc48631b32a79852d0792535710

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - pydantic >=1.9.0,<3
    - sniffio
    - python >=${{ python_min }},<4.0.0
    - httpx >=0.23.0,<1
    - attrs >=21.3.0
    - python-dateutil >=2.8.0,<3.0.0
    - typing_extensions >=4.10,<5

tests:
  - python:
      imports:
        - premai
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A client library for accessing Prem APIs
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/premAI-io/prem-python-sdk

extra:
  recipe-maintainers:
    - jan-janssen
